---
- name: Atualizar o cache do apt
  ansible.builtin.apt:
    update_cache: true

- name: Instalar xz-utils
  ansible.builtin.apt:
    name: xz-utils
    state: present

- name: Adicionar o repositório oficial do Zabbix
  ansible.builtin.apt:
    deb: https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-4+debian11_all.deb
    state: present

- name: Atualizar o cache do apt
  ansible.builtin.apt:
    update_cache: true

- name: Executar a role apache2
  ansible.builtin.include_role:
    name: apache2

- name: Instalar pacotes do Zabbix
  ansible.builtin.apt:
    name: "{{ zbx_packages }}"
    state: present

- name: Executar a role mysql-server
  ansible.builtin.include_role:
    name: mysql-server

- name: Configurar a senha do Zabbix Server
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_server.conf
    regexp: "^# DBPassword="
    line: "DBPassword=zabbix"

- name: Editar a Raíz do Documento do Apache
  ansible.builtin.replace:
    path: /etc/apache2/sites-available/000-default.conf
    regexp: "DocumentRoot /var/www/html"
    replace: "DocumentRoot /usr/share/zabbix"

- name: Instalar o pacote locales
  ansible.builtin.apt:
    name: locales
    state: present

- name: Habilitar o idioma en_US
  ansible.builtin.lineinfile:
    path: /etc/locale.gen
    regexp: "^# en_US.UTF-8 UTF-8"
    line: en_US.UTF-8 UTF-8

- name: Habilitar o idioma en_GB
  ansible.builtin.lineinfile:
    path: /etc/locale.gen
    regexp: "^# en_GB.UTF-8 UTF-8"
    line: en_GB.UTF-8 UTF-8

- name: Habilitar o idioma pt_BR
  ansible.builtin.lineinfile:
    path: /etc/locale.gen
    regexp: "^# pt_BR.UTF-8 UTF-8"
    line: pt_BR.UTF-8 UTF-8

- name: Carregar os idiomas
  ansible.builtin.shell: 
    cmd: locale-gen

- name: Habilitar os serviços do Zabbix Server
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
  loop: "{{ zbx_services }}"

- name: Reiniciar os serviços do Zabbix Server
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop: "{{ zbx_services }}"
...
