---
- name: Instalar o Zabbix Agent
  ansible.builtin.apt:
    name: zabbix-agent
    state: present

- name: Habilitar o serviço do Zabbix Agent
  ansible.builtin.service:
    name: zabbix-agent
    enabled: true

- name: Reiniciar o serviço do Zabbix Agent
  ansible.builtin.service:
    name: zabbix-agent
    state: restarted
...
