---
- name: Atualizar o cache do apt
  ansible.builtin.apt:
    update_cache: true

- name: Instalar MySQL e PyMySQL
  ansible.builtin.apt:
    name: "{{ mysql_packages }}"

- name: Habilitar o serviço do MySQL
  ansible.builtin.service:
    name: mysqld
    enabled: true

- name: Reiniciar o serviço do MySQL
  ansible.builtin.service:
    name: mysqld
    state: restarted

- name: Configurar a segurança do MySQL
  community.mysql.mysql_query:
    login_user: root
    login_unix_socket: /run/mysqld/mysqld.sock
    query:
      - ALTER USER 'root'@'localhost' IDENTIFIED BY '123Zabbix';
      - DELETE FROM mysql.user WHERE User = '';
      - DELETE FROM mysql.user WHERE User = 'root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
      - DROP DATABASE IF EXISTS test;
      - DELETE FROM mysql.db WHERE Db = 'test' OR Db = 'test\\_%';
      - FLUSH PRIVILEGES;

- name: Criar o banco de dados zabbix
  community.mysql.mysql_db:
    login_user: root
    login_password: 123Zabbix
    name: zabbix
    encoding: utf8mb4
    collation: utf8mb4_bin
    state: present

- name: Criar o usuário zabbix, que tem todos os privilégios no banco de dados zabbix
  community.mysql.mysql_user:
    login_user: root
    login_password: 123Zabbix
    name: zabbix
    password: zabbix
    priv: 'zabbix.*:ALL'
    state: present

- name: Habilitar a opção log_bin_trust_function_creators
  community.mysql.mysql_variables:
    login_user: root
    login_password: 123Zabbix
    variable: log_bin_trust_function_creators
    mode: global
    value: "1"

- name: Importar tabelas do banco de dados zabbix
  community.mysql.mysql_db:
    login_user: zabbix
    login_password: zabbix
    name: zabbix
    encoding: utf8mb4
    state: import
    target: /usr/share/zabbix-sql-scripts/mysql/server.sql.gz

- name: Desabilitar a opção log_bin_trust_function_creators após importar as tabelas do banco de dados
  community.mysql.mysql_variables:
    login_user: root
    login_password: 123Zabbix
    variable: log_bin_trust_function_creators
    mode: global
    value: "0"
...
